### ISSUE TITLE
javascript undefined errors

### ISSUE THREAD

**Issue by simonuwe** [simonuwe/oracle-apex-json-item-display#11]
Sometimes, a Javascript errors with replace on undefined object occure.

**Comment by anisriaz** [comment]
function safeReplace(str) {
    if (typeof str === 'undefined' || str === null) {
        return str; // Return as is if undefined or null
    }

    return str.replace('oldValue', 'newValue');
}

let result = safeReplace(undefined); // No error, returns undefined
console.log(result);

**Comment by simonuwe** [comment]
the "replace" error is causes by calling  
```
apex.util.escapeHTML(null)
```
That looks like a bug in Oracle-APEX.

Will be fixed in rel-0.4.1 by calling escapeHTML with not null values only (end of this week).

**Comment by simonuwe** [comment]
in rel-0.4.1
